#!/usr/bin/php
<?php

$flags = [
    '--file' => 'Location of aws credentials file. Default: ~/.aws/credentials',
    '--serail-number' => 'arn of the mfa device',
    '--token-code' => 'Code from MFA device',
    '--profile' => 'Profile to authenticate against',
    '--mfa-profile' => 'Profile to assign MFA credentials',
    '--help' => 'Show help',
];

$longOpts = [
    'file::',
    'serial-number:',
    'token-code:',
    'profile::',
    'mfa-profile:',
    'help'
];

$options = getopt('', $longOpts);

if (count($argv) === 1 || isset($options['help'])) {
    echo "Usage: aws-2fa [options]\n";
    echo "\n";
    $mask = "%0 -16s %1s\n";
    foreach ($flags as $flag => $desc) {
        printf($mask, $flag, $desc);
    }
    echo "\n";

    exit(0);
}

if (!`which aws 2>/dev/null`) {
    echo "aws command not found in PATH\n";
    exit(1);
}

if (!isset($options['mfa-profile'])) {
    echo "--mfa-profile must be set\n";
    exit(1);
}

$mfaPorfile = '[' . $options['mfa-profile'] . ']';
unset($options['mfa-profile']);

if (!isset($options['serial-number'])) {
    echo "--serial-number must be set\n";
    exit(1);
}

if (!isset($options['token-code'])) {
    echo "--token-code must be set\n";
    exit(1);
}

$credFilepath = $options['file'] ?? $_SERVER['HOME'] . '/.aws/credentials';
unset($options['file']);

if (!file_exists($credFilepath)) {
    echo "Credentials file not found at: $credFilepath\n";
    exit(1);
}


$cmd = 'aws sts get-session-token';

foreach ($options as $option => $value) {
    $cmd .= " --$option $value";
}

$output = [];
$returnCode = 0;

exec($cmd, $output, $returnCode);

if ($returnCode !== 0) {
    exit(1);
}

$creds = json_decode(implode("\n", $output), true);

$lines = file($credFilepath, FILE_IGNORE_NEW_LINES);
$newCredFileArray = [];
$foundMfaProfile = false;
$found = false;

foreach ($lines as $line) {
    if ($line === $mfaPorfile) {
        $foundMfaProfile = true;
        $found = true;
        $newCredFileArray[] = $line;
        continue;
    }

    if ($foundMfaProfile && strpos($line, '[') === 0) {
        $foundMfaProfile = false;
        $newCredFileArray[] = $line;
        continue;
    }

    if ($foundMfaProfile && strpos($line, 'aws_access_key_id') === 0) {
        $newCredFileArray[] = "aws_access_key_id = " . $creds['Credentials']['AccessKeyId'];
        continue;
    }

    if ($foundMfaProfile && strpos($line, 'aws_secret_access_key') === 0) {
        $newCredFileArray[] = "aws_secret_access_key = " . $creds['Credentials']['SecretAccessKey'];
        continue;
    }

    if ($foundMfaProfile && strpos($line, 'aws_session_token') === 0) {
        $newCredFileArray[] = "aws_session_token = " . $creds['Credentials']['SessionToken'];
        continue;
    }

    $newCredFileArray[] = $line;
}

if (!$found) {
    $newCredFileArray[] = $mfaPorfile;
    $newCredFileArray[] = "aws_access_key_id = " . $creds['Credentials']['AccessKeyId'];
    $newCredFileArray[] = "aws_secret_access_key = " . $creds['Credentials']['SecretAccessKey'];
    $newCredFileArray[] = "aws_session_token = " . $creds['Credentials']['SessionToken'];
}

file_put_contents($credFilepath, implode("\n", $newCredFileArray));

echo "Successfully updated aws MFA credentials\n";
exit(0);
